"""Add display_order to gallery

Revision ID: 07ec268e9cc6
Revises: 97ad2b12baad
Create Date: 2026-02-18 12:59:49.169372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ec268e9cc6'
down_revision = '97ad2b12baad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False,server_default="1"))

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False,server_default="1"))

    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    with op.batch_alter_table('gallery_album', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
