"""init

Revision ID: 97ad2b12baad
Revises: 
Create Date: 2026-02-16 17:08:33.106873

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '97ad2b12baad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Backfill before enforcing NOT NULL (SQLite batch rebuild)
    op.execute("UPDATE hero_slides SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;")
    op.execute("UPDATE hero_slides SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;")

    with op.batch_alter_table('hero_slides') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)


    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('banner_faculty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('banner_news',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('banner_events',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('banner_events',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('banner_news',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('banner_faculty',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
